### PR TITLE
fix: Gateway: The DevWorkspaces named differently on the Wizard vs.  Web Dashboard  #23822

### LINKED ISSUE #23822: Gateway: The DevWorkspaces named differently on the Wizard vs. Web Dashboard
When creating a DevWorkspace using Web Dashboard user may assign a custom name to the DevWorkspace,  such a custom name will be used by the Dashboard for such a DevWorkspace when listing or showing its details. 

The `Select running DevWorkspace` wizard page doesn't use such custom names, still showing a name that is automatically assigned on DevWorkspace creation:

Image

### PR DESCRIPTION
**Pull request by vrubezhny**
Fixes: https://github.com/eclipse-che/che/issues/23822

### CODE REVIEW

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspace.kt [hunk 1]
```diff
@@ -28,6 +28,11 @@ data class DevWorkspace(
             return metadata.name
         }
 
+    val displayName: String
+        get() {
+            return metadata.displayName ?: metadata.name
+        }
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspace.kt]: I believe that we should keep the model object as close as possible to the kubernetes [schema](https://github.com/yannh/kubernetes-json-schema/blob/master/master-standalone/objectmeta.json). There's no `displayName` in the kubernetes metadata schema. Furthermore I believe that `displayName` is a view-layer functionality ("how should I display the name of the DevWorkspace?"). 
Therefore I would keep it in the view-layer, in `DevWorkspaceListRenderer`. If you want it reusable, you could introduce a class `DevWorkspaceLabelUtils` or similar. 
Don't agree?

Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspace.kt]: Those labels are never stored in our 'model` object, so either we drag the whole label map into the `DevWorkspace` object and provide schema-like `'labels" property - do you mean we should do this instead of having constructed that artificial `displayName`?

Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspace.kt]: It's just that, if we're going to keep it as much closer to object-meta schema, then it worth replacing the `cheEditor` property with `annotations` map property plus a helper for getting the value for che-editor annotation, doesn't it?

Comment (adietish) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspace.kt]: I would not provide it in `DevWorkspace` which is to me a (model) class that allows access to schema properties. `displayName` does not exist in the schema. 
To me `displayName` is not a model property but a view property. I'd therefore have it in a separate helper/utility class

Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspace.kt]: Fixed. Please see the updated PR

**Review by adietish — APPROVED** [review]
