### PR TITLE
Jetbrains Gateway plugin does work when local config is using KUBECONFIG env variable

### LINKED ISSUE #23470: Jetbrains Gateway plugin doesn't work when local config is using KUBECONFIG env variable
### Describe the bug

If the developer machine is using the KUBECONFIG env variable to configure the kubernetes clusters he's using, configuration wont be understood by the gateway plugin

### Che version

7.105@latest

### Steps to reproduce

**Steps:**
1. ASSERT: have 2 files 
`~/.kubec/config`
```yaml
apiVersion: v1
clusters:
current-context: rh-sandbox
kind: Config
preferences: {}
users:
```
`~/.kube/sandbox.yaml`
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://XXXX.openshiftapps.com:6443
  name: rh-sandbox
contexts:
- context:
    cluster: rh-sandbox
    namespace: adietish-dev
    user: adietish/rh-sandbox
  name: rh-sandbox
kind: Config
preferences: {}
users:
- name: adietish/rh-sandbox
  user:
    token: sha256~XXXXX
```
2. ASSERT: have both files in a KUBECONFIG env var:
```bash
export KUBECONFIG=${HOME}/.kube/config:${HOME}/.kube/sandbox.yaml
```
3. EXEC: launch Jetbrains Gateway (with **Dev Spaces** provider installed)
4. EXEC: press **Connect to Dev Spaces** and provide **Server:** and **Token:**
5. EXEC: press **Check connection and continue**
6. ASSERT: connection is successful and you get to the following page **Select Running DevWorkspaces**
7. EXEC: select your Workspace and press **Connect**

**Result:**
Nothing happens. 
In the logs you'll find the following:
```java
java.lang.IllegalArgumentException: No server in kubeconfig
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:296)
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:278)
	at io.kubernetes.client.util.ClientBuilder.getClientBuilder(ClientBuilder.java:133)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:112)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:104)
	at io.kubernetes.client.util.ClientBuilder.defaultClient(ClientBuilder.java:86)
	at com.redhat.devtools.gateway.openshift.OpenShiftClientFactory.create(OpenShiftClientFactory.kt:25)
	at com.redhat.devtools.gateway.DevSpacesConnectionProvider.connect(DevSpacesConnectionProvider.kt:52)
	at com.jetbrains.gateway.api.GatewayConnectionProvider$Companion$connect$2.invokeSuspend(GatewayConnectionProvider.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.impl.EdtCoroutineDispatcher$wrapWithLocking$2$1.run(EdtCoroutineDispatcher.kt:71)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction$lambda$6(AnyThreadWriteThreadingSupport.kt:274)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:274)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:222)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:1009)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.openapi.application.impl.EdtCoroutineDispatcher$wrapWithLocking$$inlined$Runnable$2.run(Runnable.kt:15)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:42)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:240)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:222)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:585)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:482)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10$lambda$9(IdeEventQueue.kt:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:864)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10(IdeEventQueue.kt:306)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:958)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:958)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12(IdeEventQueue.kt:301)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:341)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Expected behavior

the gateway plugin should work if I configure my clusters using the KUBECONFIG env var.

### Runtime

Red Hat sandbox

### Screenshots

_No response_

### Installation method

other (please specify in additional context)

### Environment

macOS

### Eclipse Che Logs

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vrubezhny**
Fixes https://github.com/eclipse-che/che/issues/23470

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]
@vrubezhny, thanks for implementing the `KUBECONFIG` env. variable support.
LGTM, but I haven't tested it on my side.

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+            if (preferences != null) {
+                finalConfig["preferences"] = preferences
+            }
+
+            return mapper.writeValueAsString(finalConfig)
+        }
+
+        private fun isWindows(): Boolean {
+            return System.getProperty("os.name").lowercase(Locale.getDefault()).contains("win")
+        }
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt]: this method can be removed, the functionality already exists in jetbrains plarform: `SystemInfo.isWindows` (com.intellij.openapi.util.SystemInfo)

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+
+        private fun getKubeconfigPaths(): List<File> {
+            val kubeConfigEnv = System.getenv("KUBECONFIG") ?: return emptyList()
+            val separator = if (isWindows()) ";" else ":"
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt]: can be implemented using the platform means: `if (SystemInfo.isWindows)` or even better:
`File.pathSeparator` (java.io.File) has the correct value, no check needed.

```java
            return kubeConfigEnv
                .split(File.pathSeparator)
                .map { it.trim() }
                .filter { it.isNotEmpty() }
                .map { File(it) }
        }
```

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+import com.fasterxml.jackson.databind.ObjectMapper
+import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
+import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator
+import java.io.File
+import java.util.*
+
+class InvalidKubeConfigException(message: String) : Exception(message)
+
+class KubeConfigBuilder {
+    companion object {
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt]: if the only goal for the `companion object` is to provide "static" access, you can turn the whole `class KubeConfigBuilder` into `object KubeConfigBuilder`, you'll achieve the same goal.

```kotlin
object KubeConfigBuilder {
    fun buildEffectiveKubeConfig() {
```

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+                    selectedContextName = config["current-context"] as? String
+                }
+
+                if (preferences == null && config["preferences"] is Map<*, *>) {
+                    @Suppress("UNCHECKED_CAST")
+                    preferences = config["preferences"] as Map<String, Any>
+                }
+            }
+
+            if (selectedContextName == null) {
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt:44]: l56 - l88 could be extracted to a separate method `createConfig()`, shorten this method and thus improve readability?

**Review by adietish — APPROVED** [review]
Great stuff! Works for me :)
Added comments on minor cleanups which I implemented in a commit I added to your branch. Please review those and accept or refute them.

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt (hunk 3 above)
Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/kube/KubeConfigBuilder.kt]: Reasonable. Thanks!
