### PR TITLE
fix: refresh workspaces after (was: before) having created a new watch (23813)

### LINKED ISSUE #23813: Gateway: workspace of prior cluster are listed, too
### Describe the bug

When in gateway, you first list the workspaces for a cluster and then switch to a different cluster, you'll get the workspaces of both clusters listed.

### Che version

7.116@latest

### Steps to reproduce

**Steps:**
1. ASSERT: have workspaces with JetBrains editors in 2 different clusters.
1. EXEC: connect to the first cluster. Get to the page which lists the workspaces
2. ASSERT: you get the list of workspaces that exist for the given cluster
3. EXEC: go back to the cluster selection, select the 2nd cluster and get to the list of workspaces

**Result:**
￼The workspace of the first cluster and the ones of the 2nd cluster are both listed.

https://github.com/user-attachments/assets/d4b85acc-c461-4407-9c31-cc16bb1ff7b9

**Workaround:**
Refresh the list of workspaces

### Expected behavior

You should only see the workspaces of the cluster that you picked, not the ones of the cluster you had chosen before.

### Runtime

OpenShift

### Screenshots

_No response_

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Eclipse Che Logs

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adietish**
fixes https://github.com/eclipse-che/che/issues/23813

### CODE REVIEW

File: src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesWorkspacesStepView.kt [hunk 1]
```diff
@@ -120,59 +108,9 @@ class DevSpacesWorkspacesStepView(
         listDevWorkspaces.setEmptyText(DevSpacesBundle.message("connector.wizard_step.remote_server_connection.list.empty_text"))
 
         initListListeners(this)
-        refreshAllDevWorkspaces()
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesWorkspacesStepView.kt:123]: this is the bug: `refreshAllDevWorkspaces()` is starting the watchManager (see https://github.com/redhat-developer/devspaces-gateway-plugin/pull/284/changes#diff-0e827fc0431be7eeaee3f0fccbaefe5bc9f6954052147b20d84ced0b2f09f761L255). If there already is an existing `watchManager` for the previous cluster, it gets started and adds items from the old cluster

File: src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesWorkspacesStepView.kt [hunk 2]
```diff
@@ -120,59 +108,9 @@ class DevSpacesWorkspacesStepView(
...
-                    }
 
-                    return insertIndex
-                }
-
-            }
-        )
-        watchManager!!.start()
+        watchManager = WorkspacesWatch(devSpacesContext.client, listDWDataModel)
+        refreshAllDevWorkspaces()
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesWorkspacesStepView.kt]: this starts the (new) `watchManager` that was just created

File: src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesWorkspacesStepView.kt (hunk 1 above)
Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/view/steps/DevSpacesWorkspacesStepView.kt:123]: Confirm. This is the bug. `watchManagers` should have be cleared and nullified in `onInit()` before the call to `refreshAllDevWorkspaces()`

**Review by vrubezhny — APPROVED** [review]
Looks good to me. Thanks!
