### PR TITLE
fix: Gateway: Make it possible to restart WS when it cannot be created and launched in reasonable time

### LINKED ISSUE #23615: Gateway: Make it possible to restart WS when it cannot be created and launched in reasonable time
Under some circumstances the Remote IDE server may go into a "fail state" when it's not able to accept connections from a client,  properly report its status nor even be shutdown.

For these cases, probably the only way to fix from the client side is full DevSpaces WS Pod restart.

### PR DESCRIPTION
**Pull request by vrubezhny**
In case of Remote IDE Server doesn't return "ready" status (containing the Join Link and the projects) in reasonable time we can suggest users to restart the Pod:

image

Fixes: https://github.com/eclipse-che/che/issues/23615

### CODE REVIEW

**Review by adietish — CHANGES_REQUESTED** [review]
I tested it by killing the running `remove-dev-server` process.

I had the dialog that you implemented, after 30s. Nice!
I then hit "Cancel connection" and got an error dialog.

Image

Shouldn't we simply cancel the connection and get back to the listing of the workspaces without an error? 
If I then "OK" the error dialog I am back to the progress that I would have to cancel in order to try another connection.

image
I cannot hit "Cancel" though, UI seems frozen?

File: src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnection.kt [hunk 1]
```diff
@@ -77,6 +80,34 @@ class DevSpacesConnection(private val devSpacesContext: DevSpacesContext) {
...
+                                    "Would you like to try restarting the Pod or cancel the connection?",
+                            "Remote IDE Server Issue",
+                            arrayOf("Cancel Connection", "Restart Pod and try again"),
+                            0,  // default selected index
+                            Messages.getWarningIcon()
+                        )
+                    )
+                }
+
+                when (result.get()) {
```
[the remark this answers is not in the document]
Comment (adietish) [reply src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnection.kt]: no issues with it, can keep it, it's a matter of gusto.

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/ContainerAwareExec.kt [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+
+class ContainerAwareExec(
+    client: ApiClient,
+    private val parentScope: CoroutineScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
+) : Exec(client) {
+
+    data class ExecHandle(
+        val future: CompletableFuture<Int>,
+        val job: Job,
+        val io: IOTrio
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/ContainerAwareExec.kt]: `io` instance variable is never used, it can be removed.

```kotlin
data class ExecHandle(
        val future: CompletableFuture<Int>,
        val job: Job
)
```

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspaces.kt [hunk 3]
```diff
@@ -213,33 +202,26 @@ class DevWorkspaces(private val client: ApiClient) {
...
+                if (devWorkspace.phase !in currentPhases) {
+                    return@withTimeoutOrNull true // phase changed out of the given set
                 }
 
-                // Watch ended because server closed the stream - retry a new watch
-                delay(200)
+                delay(500)
             }
 
             @Suppress("UNREACHABLE_CODE")
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspaces.kt]: much simpler code now, no nested watchers, timeout. Major improvement, I think. Nice!

File: src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnectionProvider.kt [hunk 4]
```diff
@@ -189,30 +191,35 @@ class DevSpacesConnectionProvider : GatewayConnectionProvider {
...
+                onProgress = { value: Any ->
+                    when (val v = value) {
+                        is String -> {
+                            if (!v.isEmpty()) {
+                                indicator.text2 = v
+                            }
+                        }
+                        is ProgressCountdown.ProgressEvent -> {
+                            indicator.update(value.title, value.message, value.countdownSeconds)
+                        }
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnectionProvider.kt]: I believe that it would be better to always use a `ProgressEvent` instead of a `String` and `ProgressEvent`. This would eliminate the need of the instanceof checks (`is String` and `is ProgressCountdown.ProgressEvent`) and make code more consistent. A similar level of ease of usage could be achieved by providing an additional constructor for `ProgressEvent` that only takes a message (vs `message` and `countdownSeconds`)

**Review by adietish — COMMENTED** [review]
reviewed the code and overall major improvements imho. I nitpicked and PR'd my suggestions: https://github.com/vrubezhny/devspaces-gateway-plugin/pull/1

Next step: testing

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspaces.kt (hunk 3 above)
Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/DevWorkspaces.kt]: The watcher approach used here earlier was not cancellable... There was no way to correctly cancel `wancher.next()`  operation, so I don't use it anymore for waiting for a WS going to a desired phase.

File: src/main/kotlin/com/redhat/devtools/gateway/openshift/Pods.kt [hunk 5]
```diff
@@ -174,7 +291,7 @@ class Pods(private val client: ApiClient) {
                     copyStreams(clientSocket, forwardResult, remotePort)
                     return
                 } catch (e: Exception) {
-                    if (e is kotlin.coroutines.cancellation.CancellationException) throw e
+                    if (e.isCancellationException()) throw e
```
[the remark this answers is not in the document]
Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/openshift/Pods.kt]: JB's content assistant is an evil... As well as the mix of Kotlin and Java API... 
When typing `Cancellation...` I always get assisted and CA uses different APIs pretty each time independently of API really used (is it a coroutine, or k8s client, or my own "checkCancelled" may throw an exception) - I don't know HOW does it select from what exact class to use:  is it `kotlinx.coroutines.CancellationException` or `java.util.concurrent.CancellationException`,? Is it "kotlinx.coroutines.TimeoutCancellationException" or "java.util.concurrent.TimeoutException"?)...

So I decided to check for whatever Cancellation or Timeout may happen - the clean up usually is to be the same.

File: src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnectionProvider.kt [hunk 6]
```diff
@@ -189,30 +191,35 @@ class DevSpacesConnectionProvider : GatewayConnectionProvider {
...
-                onProgress = { message ->
-                    if (!message.isEmpty()) {
-                        indicator.text2 = message
+                onProgress = { value: Any ->
+                    when (val v = value) {
+                        is String -> {
+                            if (!v.isEmpty()) {
+                                indicator.text2 = v
+                            }
+                        }
```
[the remark this answers is not in the document]
Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnectionProvider.kt]: :+1:

File: src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnectionProvider.kt (hunk 4 above)
Comment (vrubezhny) [reply src/main/kotlin/com/redhat/devtools/gateway/DevSpacesConnectionProvider.kt]: > I believe that it would be better to always use a ProgressEvent instead of a String and ProgressEvent.

I wouldn't replace all the entrances just for two places when we need to run the backward counter in Progress Indicator (this is used on;y for 'start and wait for WS to get up and running' and for 'wait remote IDE server available'  - all the others use just a message text)

But actually yes - looks reasonable (we can probably create a helper  function that make the usage more simple and shorter.

**Review by adietish — APPROVED** [review]
Works for me. LGTM 👍
